### PR TITLE
Checking for Invalid DHCP Lease Time entries.

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
More checking for invalid DHCP Lease Time entries.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
Well, this seems strange to me. I don't know why this most recent PR #**7**, which has only 1 file changed (**YazDHCP.sh**), is shown as having **4** "Commits" & **2** "Files Changed" as if the new PR is also including commits/changes from the previous PR #**6** (which has already been merged).

Is this due to something that I inadvertently did incorrectly? 
Or, am I reading this wrong?
I just hope there are no complications.

Thanks.

**Comment by Martinski4GitHub** [comment]
OK, let's try again...

**Comment by jackyaz** [comment]
I think its because you're targeting master in this PR instead of develop

**Comment by jackyaz** [comment]
Changed merge target, please check all changes shown are expected?

**Comment by Martinski4GitHub** [comment]
> I think its because you're targeting master in this PR instead of develop
>
Ah, that explains the situation that I initially saw. Now I'm wondering how the "**master**" branch was selected as the target of the PR merge. I just double-checked and in my cloned repository all the changes are being made in my "**develop**" branch so when creating the PR, the selected target should have been your corresponding "**develop**" branch as well. Perhaps, I accidentally clicked on something that changed the target to the "master" branch. I'm still learning to navigate thru GitHub.

> Changed merge target, please check all changes shown are expected?
>
Thank you for correcting it.
I have double-checked and the committed file has the intended/expected changes. Also, I've added a change to the README file.

**Comment by Martinski4GitHub** [comment]
I was curious about the "**All checks have failed**" msg from Codacy, and thinking that perhaps I needed to "fix" something in my recent changes. However, according to the Codacy "Details" site, the cause seems to be that "**the branch develop is not being analyzed**."

YazDHCP_DevelopBranch_NotAnalized

FYI.

**Pull request merged**
