### PR TITLE
v1.0.6

### PR DESCRIPTION
**Pull request by jackyaz**
All credit for this release goes to @Martinski4GitHub

NEW "Back up & Restore custom user icons" option that provides a method to save & restore custom user icon image files and their corresponding icon-to-client associations.

Notes:
- The current implementation of "Back up & Restore custom user icons" does *not* export to or import from an external PC or client device connected to the router. Instead, it targets a directory available either on the router's JFFS partition or on a USB-attached disk drive. This target directory is where the subdirectory for backups is created and can be modified using the CLI menu (see note #3 below).

- The CLI main menu option 2 for the "Back up & Restore" functionality will show up only if there is at least one custom user icon file found in the "/jffs/usericon" directory, or if at least one backup file is found in the directory path defined for backups. If none of those 2 conditions is met, option 2 will not show up in the main menu.

- To start using the "Back up & Restore custom user icons" feature, it's highly recommended to set the target directory where the subdirectory for backups is to be located (see option "dp" in the CLI menu). For the backups subdirectory to survive a "Factory Defaults Reset" of the router, it's highly recommended to use a directory path located on a disk drive plugged into one of the router's USB ports. You don't have to have Entware installed on the USB-attached disk; any USB disk drive formatted with either NTFS or ext4 is sufficient to use as storage for the backup files.

2) FIXED issue when uninstalling YazDHCP and the "dhcp_lease" NVRAM variable could be left behind with a value that was greater than 7 days which is considered "invalid" for the stock built-in "LAN - DHCP Server" webGUI page.

3) FIXED issue where the CLI menu option to "Export NVRAM settings" was no longer available after completing the YazDHCP installation.

4) FIXED issue where the webGUI "IPv6 DNS Server" option was not made visible when the IPv6 feature was enabled.

5) General Improvements:
- Avoid restarting dnsmasq too often whenever webGUI changes are made.
- Avoid calling the CLI shell script every time "/jffs/scripts/service-event" is executed for events unrelated to YazDHCP.
- Check for possible conflicts to avoid ending up with duplicate MAC or IP address settings in dnsmasq when exporting DHCP settings from NVRAM or when applying DHCP IP address reservations from the webGUI page.
- Added code to handle a possible scenario where the NVRAM values for "dhcp_staticlist" & "custom_clientlist" variables may be missing the first angle bracket as expected in their regular syntax.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
I'll review & test the changes made to address the Shellcheck errors/warnings. I'll let you know when the regression tests are completed. It's good to hear from you.
Thanks.

**Comment by Martinski4GitHub** [comment]
After dinner, I reviewed the changes that were made to address shellcheck errors/warnings and noticed 3 problems related to fixes for shellcheck **SC2086** ("Double quote to prevent globbing and word splitting").

Every one of those 3 changes can cause failure in command execution when a parameter is a file path that contains a wildcard char [*], which when double quoted is taken not as a file pattern but as a literal asterisk, and that eventually leads to a failed command in each of the affected functions: **_movef_()**, **_remf_()** & **_list2_()**.

Examples of failures:
-----------------------
`rm -f  "/PATH/TO/DIR/FileName_*.tar"`
`ls -l  "/PATH/TO/DIR/FileName_*.tar"`
`mv -f  "/PATH/TO/DIR/FileName_*.tar" "/PATH/TO/NEW/DIR"`

Good examples:
-----------------------
`rm -f  /PATH/TO/DIR/FileName_*.tar`
`ls -l  /PATH/TO/DIR/FileName_*.tar`
`mv -f  /PATH/TO/DIR/FileName_*.tar "/PATH/TO/NEW/DIR"`

I've submitted PR #22 to revert those changes and add descriptions to explain the reasons for explicitly disabling shellcheck **SC2086**.

**Comment by jackyaz** [comment]
Thanks for reviewing. Are you happy for go-live?

**Comment by Martinski4GitHub** [comment]
> Thanks for reviewing. Are you happy for go-live?
>
Let me run some regression tests this evening just to double-check. I'll let you know when completed.
Thanks.

**Comment by Martinski4GitHub** [comment]
I've submitted PR #23. After code changes are approved & merged, I'm happy with going into production release.
I ran regression tests & verification & they all went well, so it's all good from here.
Cheers mate!

**Pull request merged**
